image: maven:3.6.3-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - 'apt-get update && apt install sshpass'

stages:
  - build
  - test
  - deploy


cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS  compile

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test -P Unit

deploy-master:
  stage: deploy
  script:
    - mvn assembly:assembly
    - sshpass -p "PASSWORD" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 20012 target/mvntfg-1.0-jar-with-dependencies.jar usuario@virtual.lab.inf.uva.es:C:\Users\Usuario\AppData\Local\semanticmerge 
    - sshpass -p "PASSWORD" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no usuario@virtual.lab.inf.uva.es -p 20012 "cd /cygdrive/c/Users/Usuario/AppData/Local/semanticmerge/ && ./script.bat && exit"
  only:
    - master
####
deploy-develop:
  stage: deploy
  script:
    - mvn assembly:assembly
    - sshpass -p "$password" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 20012 target/mvntfg-1.0-jar-with-dependencies.jar usuario@virtual.lab.inf.uva.es:C:\Users\Usuario\AppData\Local\semanticmerge 
    - sshpass -p "$password" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no usuario@virtual.lab.inf.uva.es -p 20012 "cd /cygdrive/c/Users/Usuario/AppData/Local/semanticmerge/ && ./script.bat && exit"
  only:
    - develop